//! Commands where the harness has no command surface. Codex deprecated
//! `~/.codex/prompts` in favor of skills, so a declared command lands on the
//! skill surface as a generated skill, and the lock records what was
//! actually written so removal and refresh target it.
#![cfg(unix)]

#[path = "../../test_util.rs"]
mod test_util;
use test_util::source_path;

use std::fs;
use std::path::{Path, PathBuf};

use kendex_core::apply;
use kendex_core::engine::{audit, ops};
use kendex_core::env::{Env, FakeOs};
use kendex_core::model::Scope;
use serde_json::Value;

const SHIP: &str = "---\ndescription: Ship the branch\n---\n\nRun the release checklist.\n";

struct Fixture {
    _tmp: tempfile::TempDir,
    env: Env,
    scope: Scope,
    project: PathBuf,
    source: PathBuf,
}

/// A project whose catalog carries the `ship` command. `harnesses` and
/// `declarations` are written into the manifest verbatim.
#[allow(clippy::unwrap_used)]
fn fixture(harnesses: &str, declarations: &str) -> Fixture {
    let tmp = tempfile::tempdir().unwrap();
    // Canonical up front: macOS reaches its temp dirs through a symlink,
    // and the engine hands back canonical paths.
    let home = tmp.path().canonicalize().unwrap();
    let env = Env::fake(&home, FakeOs::Linux);
    let project = home.join("dev/app");
    fs::create_dir_all(project.join(".claude")).unwrap();

    let source = home.join("catalog");
    fs::create_dir_all(source.join("commands")).unwrap();
    fs::write(source.join("commands/ship.md"), SHIP).unwrap();
    // Commands install only from a catalog that declares kendex's layout.
    fs::write(source.join("kendex.toml"), "is_source_catalog = true\n").unwrap();

    fs::write(
        project.join("kendex.toml"),
        format!(
            "schema = 6\n\n[sources.cat]\n{}\n\n[install]\nharnesses = [{harnesses}]\nmethod = \"symlink\"\n\n{declarations}",
            source_path(&source)
        ),
    )
    .unwrap();

    Fixture {
        env,
        scope: Scope::Project {
            root: project.clone(),
        },
        project,
        source,
        _tmp: tmp,
    }
}

#[allow(clippy::unwrap_used)]
fn add_skill(f: &Fixture, name: &str, body: &str) {
    let dir = f.source.join("skills").join(name);
    fs::create_dir_all(&dir).unwrap();
    fs::write(
        dir.join("SKILL.md"),
        format!("---\nname: {name}\ndescription: {name}\n---\n\n{body}\n"),
    )
    .unwrap();
}

#[allow(clippy::unwrap_used)]
fn apply_now(f: &Fixture) {
    let report = audit(&f.env, &f.scope).unwrap();
    apply::execute(&f.env, &report.plan).unwrap();
}

#[allow(clippy::unwrap_used)]
fn toggle(f: &Fixture, name: &str, enabled: bool) {
    let report = ops::toggle(&f.env, &f.scope, &[name.to_owned()], None, enabled).unwrap();
    apply::execute(&f.env, &report.plan).unwrap();
}

#[allow(clippy::unwrap_used)]
fn json(path: &Path) -> Value {
    serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap()
}

fn lock(f: &Fixture) -> Value {
    json(&f.project.join(".kendex-lock.json"))
}

#[allow(clippy::unwrap_used)]
fn is_clean(f: &Fixture) -> bool {
    audit(&f.env, &f.scope).unwrap().drift.is_empty()
}

#[test]
#[allow(clippy::unwrap_used)]
fn a_command_reaches_claude_as_a_file_and_codex_as_a_skill() {
    let f = fixture(
        "\"claude\", \"codex\"",
        "[commands.ship]\nsource = \"cat\"\n",
    );
    apply_now(&f);

    assert_eq!(
        fs::read_to_string(f.project.join(".claude/commands/ship.md")).unwrap(),
        SHIP
    );

    let text = fs::read_to_string(f.project.join(".agents/skills/ship/SKILL.md")).unwrap();
    assert!(
        text.starts_with("---\nname: ship\ndescription: Ship the branch\n---\n"),
        "{text}"
    );
    assert!(text.contains("Generated by kendex"), "{text}");
    assert!(text.contains("Run the release checklist."), "{text}");

    let lock = lock(&f);
    let emitted = &lock["entries"]["command:ship:codex"]["emitted"];
    assert_eq!(emitted["kind"], "skill");
    assert_eq!(emitted["name"], "ship");
    assert_eq!(
        emitted["paths"][0],
        Value::from(
            f.project
                .join(".agents/skills/ship")
                .display()
                .to_string()
                .as_str()
        )
    );
    assert!(
        lock["entries"]["command:ship:claude"]
            .get("emitted")
            .is_none(),
        "claude writes a command file, not an emitted artifact"
    );
    assert!(is_clean(&f));
}

#[test]
#[allow(clippy::unwrap_used)]
fn a_command_installs_as_a_skill_at_global_scope_too() {
    let f = fixture("\"codex\"", "");
    let manifest = f.env.global_manifest_file();
    fs::create_dir_all(manifest.parent().unwrap()).unwrap();
    fs::write(
        &manifest,
        format!(
            "schema = 6\n\n[sources.cat]\n{}\n\n[install]\nharnesses = [\"codex\"]\nmethod = \"symlink\"\n\n[commands.ship]\nsource = \"cat\"\n",
            source_path(&f.source)
        ),
    )
    .unwrap();

    let report = audit(&f.env, &Scope::Global).unwrap();
    apply::execute(&f.env, &report.plan).unwrap();

    // Codex reads `~/.agents/skills` globally, so that is where the
    // generated skill lands, not in a directory of its own.
    let skill = f.env.global_skills_dir().join("ship/SKILL.md");
    assert!(
        fs::read_to_string(&skill)
            .unwrap()
            .contains("Run the release checklist."),
        "{}",
        skill.display()
    );
    assert!(audit(&f.env, &Scope::Global).unwrap().drift.is_empty());
}

#[test]
#[allow(clippy::unwrap_used)]
fn a_skill_of_the_same_name_keeps_it_and_the_command_is_renamed() {
    let f = fixture(
        "\"codex\"",
        "[skills.ship]\nsource = \"cat\"\n\n[commands.ship]\nsource = \"cat\"\n",
    );
    add_skill(&f, "ship", "The real skill.");

    let report = audit(&f.env, &f.scope).unwrap();
    assert!(
        report
            .warnings
            .iter()
            .any(|w| w.name == "ship" && w.message.contains("ship__command")),
        "{:?}",
        report.warnings
    );
    apply::execute(&f.env, &report.plan).unwrap();

    let skills = f.project.join(".agents/skills");
    assert!(
        fs::read_to_string(skills.join("ship/SKILL.md"))
            .unwrap()
            .contains("The real skill.")
    );
    assert!(
        fs::read_to_string(skills.join("ship__command/SKILL.md"))
            .unwrap()
            .contains("Run the release checklist.")
    );
    assert_eq!(
        lock(&f)["entries"]["command:ship:codex"]["emitted"]["name"],
        "ship__command"
    );
    assert!(is_clean(&f));
}

#[test]
#[allow(clippy::unwrap_used)]
fn a_taken_rename_falls_through_to_the_shorter_suffix() {
    let f = fixture("\"codex\"", "[commands.ship]\nsource = \"cat\"\n");
    add_skill(&f, "ship", "The real skill.");
    add_skill(&f, "ship__command", "Something else entirely.");
    apply_now(&f);

    assert!(
        fs::read_to_string(f.project.join(".agents/skills/ship__cmd/SKILL.md"))
            .unwrap()
            .contains("Run the release checklist.")
    );
    assert!(is_clean(&f));
}

#[test]
#[allow(clippy::unwrap_used)]
fn toggling_a_command_off_parks_the_generated_skill() {
    let f = fixture("\"codex\"", "[commands.ship]\nsource = \"cat\"\n");
    apply_now(&f);
    let tree = f.project.join(".agents/skills/ship");
    assert!(tree.join("SKILL.md").is_file());

    toggle(&f, "ship", false);
    assert!(!tree.join("SKILL.md").exists());
    assert!(
        fs::read_to_string(tree.join("SKILL.md.disabled"))
            .unwrap()
            .contains("Run the release checklist.")
    );
    assert!(is_clean(&f), "disabled is a state, not drift");

    toggle(&f, "ship", true);
    assert!(tree.join("SKILL.md").is_file());
    assert!(!tree.join("SKILL.md.disabled").exists());
}

#[test]
#[allow(clippy::unwrap_used)]
fn removing_a_command_takes_the_generated_skill_with_it() {
    let f = fixture("\"codex\"", "[commands.ship]\nsource = \"cat\"\n");
    apply_now(&f);
    let tree = f.project.join(".agents/skills/ship");
    assert!(tree.is_dir());

    let report = ops::remove(&f.env, &f.scope, &["ship".to_owned()], None, false).unwrap();
    apply::execute(&f.env, &report.plan).unwrap();
    assert!(!tree.exists(), "the emitted tree is what comes off disk");
    assert!(is_clean(&f));
}

#[test]
#[allow(clippy::unwrap_used)]
fn harnesses_that_only_read_commands_get_nothing_written() {
    let f = fixture("\"cursor\"", "[commands.ship]\nsource = \"cat\"\n");
    let report = audit(&f.env, &f.scope).unwrap();
    assert!(report.plan.ops.is_empty(), "{:?}", report.plan.ops);
    apply::execute(&f.env, &report.plan).unwrap();

    for dir in [".cursor", ".agents"] {
        assert!(!f.project.join(dir).exists(), "{dir} was written to");
    }
}

/// The cross-read warning names a tool only when that tool's loader would
/// take the tree. Reading the directory is not enough: a name carrying
/// `__` is unloadable where names must be lower-kebab, so OpenCode and
/// Copilot are offered nothing and naming them would warn about a command
/// nobody can reach. Pi takes any name, so it is named.
///
/// The pair is the same warning over a plain name, which those loaders do
/// take — without it the assertion would pass on a warning that had simply
/// stopped naming anyone.
#[test]
#[allow(clippy::unwrap_used)]
fn the_cross_read_warning_skips_a_loader_that_would_reject_the_name() {
    let rejecting = ["OpenCode", "GitHub Copilot"];

    let f = fixture(
        "\"codex\"",
        "[skills.ship]\nsource = \"cat\"\n\n[commands.ship]\nsource = \"cat\"\n",
    );
    add_skill(&f, "ship", "The real skill.");
    let reach = cross_read_warning(&f);
    assert!(
        reach.contains("ship__command"),
        "the collision fallback is what is installed: {reach}"
    );
    assert!(reach.contains("Pi"), "Pi takes any name: {reach}");
    for tool in rejecting {
        assert!(
            !reach.contains(tool),
            "{tool} rejects a `__` name and cannot offer it: {reach}"
        );
    }

    let plain = fixture("\"codex\"", "[commands.ship]\nsource = \"cat\"\n");
    let reach = cross_read_warning(&plain);
    for tool in rejecting {
        assert!(
            reach.contains(tool),
            "{tool} reads the tree and takes a plain name: {reach}"
        );
    }
}

/// The one warning that says which other tools are offered the command.
#[allow(clippy::unwrap_used)]
fn cross_read_warning(f: &Fixture) -> String {
    let report = audit(&f.env, &f.scope).unwrap();
    let found: Vec<String> = report
        .warnings
        .iter()
        .filter(|w| w.message.contains("also read"))
        .map(|w| w.message.clone())
        .collect();
    assert_eq!(found.len(), 1, "{:?}", report.warnings);
    found.into_iter().next().unwrap()
}
